### ISSUE TITLE
Be careful to avoid a TypeError when detect options support

### ISSUE THREAD

**Issue by fengyuanchen** [lifaon74/events-polyfill#3]
Check out this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Getter_only

**Comment by lifaon74** [comment]
I don't understand what you mean ? I don't use try/catch or TypeError, so what's the problem ?

**Comment by lifaon74** [comment]
If you mean, I should use setter. It's not mandatory because options are readonly.
