### ISSUE TITLE
Fails in Safari 11.1.2

### ISSUE THREAD

**Issue by andrewgadziksonos** [lifaon74/events-polyfill#4]
Loading this polyfill in Safari is giving us an JS console error,

`[Error] TypeError: Property description must be an object`

**Comment by lifaon74** [comment]
Please provide the line, column and file. In any case, the full polyfill doesn't contain the keyword 'description' so I guess this bug is on your side. I close the issue until you give me more informations

**Comment by andrewgadziksonos** [comment]
https://github.com/lifaon74/events-polyfill/blob/49412995a9ed97ede6e44390312fd1c44f40b70a/src/constructors/PointerEvent.js#L65

```
Object.defineProperty(
      PointerEvent.prototype,
      'twist',
      Object.getOwnPropertyDescriptor(PointerEvent.prototype, 'rotation')
    )
```

This is the code causing the issue.  There's no property named `rotation` on the PointerEvent prototype, `getOwnPropertyDescriptor` returns undefined, causing the TypeError

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor

https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent

**Comment by andrewgadziksonos** [comment]
@lifaon74 Please reopen

**Comment by andrewgadziksonos** [comment]
@lifaon74 here's the fix,

`Object.getOwnPropertyDescriptor(PointerEvent.prototype, 'rotation') || {}`

Not sure how to submit a PR, nor do I have access to push to a branch (no instructions)

**Comment by lifaon74** [comment]
I fixed it pushed it on git on npm could you test pls
